Update env0.yml

diff --git a/misc/null-resource/env0.yml b/misc/null-resource/env0.yml
--- a/misc/null-resource/env0.yml
+++ b/misc/null-resource/env0.yml
@@ -5,4 +5,12 @@ deploy:
     terraformInit:
       after:
         - name: check my
-          run: echo my
+          run: |
+          # Expected value
+          EXPECTED_VALUE="secret1"
+          
+          # Check if ENV_VAR matches the expected value
+          if [ "$SECRET" != "$EXPECTED_VALUE" ]; then
+            echo "Error: ENV_VAR is not equal to '$EXPECTED_VALUE'."
+            exit 1
+          fi
